### ISSUE TITLE
Project Structure Definition

### ISSUE THREAD

**Issue by LuchoBazz** [LuchoBazz/express-ts-rest-starter-kit#3]
### Tasks
- [x] Add Docker and docker-compose DB config
- [x] Add Prisma configuration
- [x] Add Basics Prisma Schemas
  - [x] Create Organizations DB Schema
  - [x] Create Users DB Schema
  - [x] Create Organizations Table
  - [x] Create Feature Flags Table
  - [x] Create Configurations Table
  - [x] Create Auth Token Status Table
  - [x] Create Users table
  - [x] Create Roles Table
  - [x] Create Permissions table
- [x] Add Prisma commands in README.md
- [x] Add CRUD interactor for Feature Flags
- [x] Add CRUD interactor for Configurations
- [x] Add CRUD interactor for Organizations (Create Read and Update)
- [x] Add  interactor for Roles
  - [x] Create Prisma Seed for create Roles
  - [x] Get All Permissions of a specific Role (¿Cache? ¿Interactor/UseCase/Service?)
- [x] Add CRUD interactor for Permissions
  - [x] Create Prisma Seed for create Permissions
  - [x] Add Permission a Specific Role
- [ ] Add Cache in Permissions by Role
- [x] Add Authentication
  - [x] Firebase Config
  - [x] Supabase Config
- [x] Add Subscription Prisma Schemas
  - [x] Create subscription DB Schema
  - [x] Create subscription plan DB Schema
  - [x] Create payment DB Schema
  - [x] Create Subscription Service/Interactor/Controller
  - [x] Create Subscription Plan Service/Interactor/Controller
  - [x] Create Payment Service/Interactor/Controller
 
### Tests

- [x] Add Examples for Organizations
- [x] Add Examples for Feature Flags
- [x] Add Examples for Configurations
- [x] Add Examples for Users
- [x] Add Examples for Roles
- [x] Add Examples for Permissions

### Future
...

#### Tests

- [x] Add Examples for Subscription
- [x] Add Examples for Subscription Plan
- [x] Add Examples for Payment

### Deprecated

- [ ] Add CRUD interactor for Roles_
  - [ ] Create Role
  - [ ] Delete Role
- [ ] Add CRUD interactor for Permissions
  - [ ] Create Permission
  - [ ] Delete Permission

**Comment by LuchoBazz** [comment]
```text
/src
│
├── /app
│   ├── app.ts               # Configuración y arranque de la aplicación
│   ├── routes.ts            # Definición de rutas (se conecta con los controladores)
│   └── server.ts            # Configuración del servidor Express
│
├── /core                    # Dominio principal (lógica de negocio)
│   ├── /entities            # Entidades del dominio
│   │   └── user.entity.ts   # Entidad de ejemplo (User)
│   ├── /services            # Servicios que contienen la lógica de negocio
│   │   └── user.service.ts  # Servicio de ejemplo (UserService)
│   ├── /repositories        # Interfaces de persistencia (puertos)
│   │   └── user.repository.ts
│   └── /use_cases           # Casos de uso (lógica de aplicación)
│       └── create_user.use_case.ts # Caso de uso de ejemplo (Crear Usuario)
│
├── /adapters                # Adaptadores (implementaciones de puertos)
│   ├── /api                 # Adaptadores de API (controladores para la entrada/salida HTTP)
│   │   ├── user.controller.ts # Controlador para manejar requests relacionadas con usuarios
│   │   └── error.handler.ts    # Manejo de errores global
│   ├── /persistence         # Adaptadores de persistencia (implementación de interfaces de repositorios)
│   │   └── user.prisma.ts   # Implementación del repositorio usando Prisma
│   └── /mappers             # Mapeadores de datos (si es necesario para traducir entre capas)
│       └── user.mapper.ts   # Mapeador de User entre capas de datos y dominio
│
├── /infrastructure          # Configuración de infraestructura y dependencias
│   ├── /database            # Configuración de la base de datos
│   │   └── prisma.ts        # Conexión a la base de datos usando Prisma
│   ├── /http                # Configuración de Express y middlewares
│   │   └── express.ts       # Configuración de middlewares de Express
│   ├── /logger              # Logger (como Winston o similar)
│   │   └── logger.ts        # Configuración del logger
│   └── /env                 # Configuración de variables de entorno
│       └── config.ts        # Archivo de configuración de entorno
│
└── /tests                   # Pruebas unitarias e integración
    ├── /unit                # Pruebas unitarias para los servicios del dominio
    ├── /integration         # Pruebas de integración para las APIs y bases de datos
    └── /mocks               # Mock de dependencias para las pruebas

```

**Comment by LuchoBazz** [comment]
```text
├── /shared
│   ├── /utils
│   └── /constants
```
